spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    jpa:
      hibernate:
        dll-auto: update

      generate-ddl: true

    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: StringUsadaParaGerarToken
  expiration: 180000

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/helpdesk
    username: root
    password:

  jpa:
    hibernate:
      dll-auto: none

    generate-ddl: true

    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: StringUsadaParaGerarToken
  expiration: 180000
